markdown: kramdown
url: ''
baseurl: null
title: Coding Flamingo
description: Learn to code with Coding Flamingo
site-image: /WhatATheme/assets/images/coding-flamingo-01.jpg
site-keywords: 'Coding, Tutorials, Azure, AWS, Blazor, .NET'
favicon-url: 'https://codingflamingo.blob.core.windows.net/codingflamingo/favicon.ico'
heroimage: >-
  https://codingflamingo.blob.core.windows.net/codingflamingo/coding-flamingo-01.jpg
email: codingflamingo@gmail.com
linkedin_username: igalfsg
github_username: coding-flamingo
youtube_channel_id: UCjGgqULI1EX0VEoizrD6PYA
reddit_username: TacoT999
google-analytics: UA-59281202-3
author-name: Coding Flamingo
author-image: >-
  https://codingflamingo.blob.core.windows.net/codingflamingo/coding-flamingo-07.png
author-about: >-
  Coding Flamingo is a YouTube channel and blog that I created to share coding
  best practices.
author-url: 'https://github.com/coding-flamingo'
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-admin
  - jekyll-feed
permalink: 'blog/:title'
compress_html:
  clippings: all
defaults:
  - scope:
      type: posts
    values:
      layout: post
      post-image: ''
      description: ''
      tags:
        - ''
  - scope:
      type: pages
    values:
      layout: page
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
